apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: services
  name: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: services
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: services
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - image: southamerica-west1-docker.pkg.dev/conexia-486401/conexia-registry/services
          name: services
          env:
            - name: NODE_ENV
              value: "production"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: DATABASE_URL
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: SMTP_HOST
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_SECURE
              value: "false"
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: SMTP_PASS
            - name: EMAIL_FROM
              value: "conexianoreply@gmail.com"
            - name: FRONTEND_URL
              value: "https://conexia-front.vercel.app"
            - name: API_BASE_URL
              value: https://api.34.36.140.43.nip.io
            - name: MERCADOPAGO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: MERCADOPAGO_ACCESS_TOKEN
            - name: MERCADOPAGO_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: MERCADOPAGO_PUBLIC_KEY
            - name: MERCADOPAGO_SELLER_COLLECTOR_ID
              valueFrom:
                secretKeyRef:
                  name: services-secrets
                  key: MERCADOPAGO_SELLER_COLLECTOR_ID
            - name: GCS_PROJECT_ID
              value: "conexia-486401"
            - name: GCS_KEY_FILE
              value: "/etc/gcs/key.json"
            - name: GCS_SERVICE_IMAGES_BUCKET
              value: "conexia-service-images"
            - name: ADMIN_EMAIL
              value: "conexia.contact@gmail.com"
          volumeMounts:
            - name: gcs-key
              mountPath: /etc/gcs
              readOnly: true
          resources: {}
      volumes:
        - name: gcs-key
          secret:
            secretName: gcs-key-secret
status: {}
